---
title: "Markdown2"
author: "Cameron Atighetchi"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: TRUE
    toc_float: TRUE
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      message = FALSE,
                      warning = FALSE,
                      fig.path = "../Output/")
```

# Loading Packages
```{r}
library(tidyverse)
library(here)
library(palmerpenguins)
```

# Creating a Plot with Penguin data
```{r PenguinMarkdown, fig.cap="This is a scatterplot of penguins"} 
ggplot(data = penguins, aes(x = bill_length_mm, 
                            y = bill_depth_mm)) +
  geom_point()
```

# Hand-written Table  

| Table | Session | Topic |
| :-----|:-------:|------:|
| 24    | 21      | 32    |

# Using Kable to make table  
```{r}
library(kableExtra)
penguins %>%
  group_by(species) %>%
  summarise(billmean = mean(bill_length_mm, na.rm = TRUE)) %>%
  kbl() %>% # make it a kable table
  kable_classic() %>%
  row_spec(2, bold = T, color = "black", background = "yellow") %>%
  kable_styling(full_width = FALSE)

```






