## Created by: Cameron Atighetchi #####
# Created on: 2023-02-07#####
## Intro to Plot R ###########
####################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################
### Load Libraries & Data ########################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################
library(palmerpenguins)
glimpse(penguins)
###### Functions #################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################
##ggplot(data = penguins) <-- Load ggplot
##ggplot(data = penguins, mapping = aes (x = bill_depth_mm)) <-- Creates x-axis Gridlines
##ggplot(data = penguins, mapping = aes (x = bill_depth_mm, y = bill_length_mm)) <-- Creates y-axis Gridlines
###ggplot(data = penguins, mapping = aes (x = bill_depth_mm, y = bill_length_mm)) + geom_point () <-- Represents each observation with a point
##ggplot(data = penguins, mapping = aes (x = bill_depth_mm, y = bill_length_mm, color = species)) + geom_point () <-- Map species to the color of each point
##ggplot(data = penguins, mapping = aes (x = bill_depth_mm, y = bill_length_mm, color = species)) + geom_point () + labs(title = "Bill depth and length") <-- Title the plot "Bill depth and length"
##ggplot(data = penguins, mapping = aes (x = bill_depth_mm, y = bill_length_mm, color = species)) + geom_point () + labs(title = "Bill depth and length", subtitle = "Dimensions for Adelie, Chinstrap, and Gentoo Penguins") <-- Add the subtitle "Dimensions...
##ggplot(data = penguins, mapping = aes (x = bill_depth_mm, y = bill_length_mm, color = species)) + geom_point () + labs(title = "Bill depth and length", subtitle = "Dimensions for Adelie, Chinstrap, and Gentoo Penguins", x = "Bill Depth (mm)", y = "Bill Length (mm)") <-- Label the x and y axes
##ggplot(data = penguins, mapping = aes (x = bill_depth_mm, y = bill_length_mm, color = species)) + geom_point () + labs(title = "Bill depth and length", subtitle = "Dimensions for Adelie, Chinstrap, and Gentoo Penguins", x = "Bill Depth (mm)", y = "Bill Length (mm)", color = "Species") <-- Label the legend Species
##ggplot(data = penguins, mapping = aes (x = bill_depth_mm, y = bill_length_mm, color = species)) + geom_point () + labs(title = "Bill depth and length", subtitle = "Dimensions for Adelie, Chinstrap, and Gentoo Penguins", x = "Bill Depth (mm)", y = "Bill Length (mm)", color = "Species", caption = "Source: Palmer Station LTER / palmerpenguins package") <-- Add a caption for source of data
##ggplot(data = penguins, mapping = aes (x = bill_depth_mm, y = bill_length_mm, color = species)) + geom_point () + labs(title = "Bill depth and length", subtitle = "Dimensions for Adelie, Chinstrap, and Gentoo Penguins", x = "Bill Depth (mm)", y = "Bill Length (mm)", color = "Species", caption = "Source: Palmer Station LTER / palmerpenguins package") + scale_color_viridis_d() ##Finally, use a discrete color scale for color blind ppl
##ggplot(data = penguins, mapping = aes (x = bill_depth_mm, y = bill_length_mm, color = species, shape = island)) + geom_point () + labs(title = "Bill depth and length", subtitle = "Dimensions for Adelie, Chinstrap, and Gentoo Penguins", x = "Bill Depth (mm)", y = "Bill Length (mm)", color = "Species", caption = "Source: Palmer Station LTER / palmerpenguins package") + scale_color_viridis_d() ## Map a different variable than color
##ggplot(data = penguins, mapping = aes (x = bill_depth_mm, y = bill_length_mm, color = species, shape = species)) + geom_point () + labs(title = "Bill depth and length", subtitle = "Dimensions for Adelie, Chinstrap, and Gentoo Penguins", x = "Bill Depth (mm)", y = "Bill Length (mm)", color = "Species", caption = "Source: Palmer Station LTER / palmerpenguins package") + scale_color_viridis_d() ## Map the same variable as color
##ggplot(data = penguins, mapping = aes (x = bill_depth_mm, y = bill_length_mm, color = species, size = body_mass_g)) + geom_point () + labs(title = "Bill depth and length", subtitle = "Dimensions for Adelie, Chinstrap, and Gentoo Penguins", x = "Bill Depth (mm)", y = "Bill Length (mm)", color = "Species", caption = "Source: Palmer Station LTER / palmerpenguins package") + scale_color_viridis_d() ## Adds different size dots based on body weight
ggplot(data = penguins, mapping = aes (x = bill_depth_mm, y = bill_length_mm, color = species, size = body_mass_g, alpha = flipper_length_mm)) + geom_point () + labs(title = "Bill depth and length", subtitle = "Dimensions for Adelie, Chinstrap, and Gentoo Penguins", x = "Bill Depth (mm)", y = "Bill Length (mm)", color = "Species", caption = "Source: Palmer Station LTER / palmerpenguins package") + scale_color_viridis_d() ## Makes it transparent by flipper length

####### Faceting #######################################################################################################################################################################################################################################################################################################################################################################################################################################################################
ggplot (penguins, aes (x = bill_depth_mm, y = bill_length_mm)) + geom_point () + facet_grid (species~sex) ##Gives us a faceted grid view of species with x and y axes differed by sex of the penguin
ggplot (penguins, aes (x = bill_depth_mm, y = bill_length_mm)) + geom_point () + facet_wrap(~ species, ncol=2) ##Gives a vertical wrapped around view of species & make it two columns
ggplot (penguins, aes (x = bill_depth_mm, y = bill_length_mm, color = species)) + geom_point () + scale_color_viridis_d () + facet_wrap(species ~ sex) ## Adds color and legend to points
ggplot (penguins, aes (x = bill_depth_mm, y = bill_length_mm, color = species)) + geom_point () + scale_color_viridis_d () + facet_wrap(species ~ sex) + guides(color = FALSE) ## Gets rid of Legend

##################################################################################################################################################################################################################################################################################################################################################################################################################################################